[[plugins]]
  package = ["netlify-plugin-inline-functions-env", "netlify-plugin-package"]
  [plugins.inputs.package]
    include = ["aws-sdk"]

[plugins.inputs]
  include = "netlify/functions/**/*"
  exclude = []