[build]
  functions = "netlify/functions"

[[plugins]]
  package = "netlify-plugin-inline-functions-env"

[plugins.inputs]
  include = "netlify/functions/**/*"
  exclude = []

[functions]
  external_node_modules = ["aws-sdk"]