[[plugins]]
  package = "netlify-plugin-inline-functions-env"

[plugins.inputs]
  include = "netlify/functions/**/*"
  exclude = []

[[plugins]]
  package = "netlify-plugin-package"
  [plugins.inputs.package]
    include = ["aws-sdk"]

[functions]
  external_node_modules = ["aws-sdk"]