[build]
  command = "npm install aws-sdk && npm run build"

[[plugins]]
  package = "netlify-plugin-inline-functions-env"

[plugins.inputs]
  include = "netlify/functions/**/*"
  exclude = []

[[plugins]]
  package = "netlify-plugin-package"
  [plugins.inputs.package]
    include = ["aws-sdk"]