[[plugins]]
  package = "netlify-plugin-package"
  [plugins.inputs.package]
    include = ["aws-sdk"]

[[plugins]]
  package = "netlify-plugin-inline-functions-env"

[plugins.inputs]
  include = "netlify/functions/**/*"
  exclude = []
